version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test
