version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: | 
            dotnet test KenticoKontent.Delivery.Tests
            dotnet test KenticoKontent.Delivery.Rx.Tests
